### ISSUE TITLE
THIS USER IS PREMIUM!

### ISSUE THREAD

**Issue by mikedhanson** [Michael-K-Stein/SpotiFile#5]
pip3 install -r requirements.txt
python3 main.py

```
Traceback (most recent call last):
  File "/Users/michaelhanson/Downloads/SpotiFile/main.py", line 2, in <module>
    from webgui import app
  File "/Users/michaelhanson/Downloads/SpotiFile/webgui.py", line 4, in <module>
    from spotify_mass_download import full_download, console, download_all_categories_playlists
  File "/Users/michaelhanson/Downloads/SpotiFile/spotify_mass_download.py", line 15, in <module>
    client.get_me()
  File "/Users/michaelhanson/Downloads/SpotiFile/spotify_client.py", line 92, in get_me
    raise SpotifyClientException('THIS USER IS PREMIUM!')
exceptions.SpotifyClientException: THIS USER IS PREMIUM!
```

**Comment by Michael-K-Stein** [comment]
SpotiFile will not let you use a premium account. This is to avoid the account being suspended. Just open another one.
